---
services:
  FedoraMatei:
    image: lscr.io/linuxserver/webtop:fedora-mate
    container_name: fedoramate
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - CUSTOM_PORT=5800
      - CUSTOM_HTTPS_PORT=5900
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Fedora Mate #optional
    volumes:
      - /path/to/data:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 5800:5800
      - 5900:5900
    shm_size: "1gb" #optional
    restart: unless-stopped